### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by zero0nee** [tiangolo/full-stack-flask-couchbase#4]
UPDATE
I posted this in the wrong repo. I'm actually using [full-stack-fastapi-couchbase](https://github.com/tiangolo/full-stack-fastapi-couchbase). Will post it there. 

Hi! 

When I try to create a new user, using `POST /api/v1/users/` I get the response `422 Unprocessable Entity`, and the backend will just log:

 ` [2019-02-28 16:15:06 +0000] [45] [INFO] ('172.20.0.2', 51610) - "POST /api/v1/users/ HTTP/1.1" 422 `

Anyone else has this problem. I've just used the template generator without any customisation.

**Comment by tiangolo** [comment]
Cool! I'll close this one now then.
